---
title: "4_alpha_diversity_regression"
author: "Pedro Beschoren"
date: "2023-02-02"
output: html_document
editor_options: 
  chunk_output_type: console
---



# 0 - load libraries
```{r}

#load necessary libraries
library(phyloseq)
library(ggplot2)
library(vegan)
library(tidyr)
library(decontam)
library(dplyr)
library(ggrepel)
library("svglite")


# increases memory limit used by R
memory.limit(size = 350000)


```

# load data and subset samples

```{r}
# laod rarefied data
load(file = "./Data/rarefied_BacFun_ps_l.RData")

# remove treatment N (no plant)
rarefied_BacFun_ps_l<-lapply(rarefied_BacFun_ps_l, function (x) subset_samples(x, frass_treatment!="N"))

# remove Frass sample type (no plant/soil)
rarefied_BacFun_ps_l<-lapply(rarefied_BacFun_ps_l, function (x) subset_samples(x, sample_type !="frass"))

#split by sample type
rarefied_BacFun_ps_sampletype_FrassTrestemnt_l<-lapply(rarefied_BacFun_ps_l, function (x)metagMisc::phyloseq_sep_variable(x, variable = c("sample_type", "frass_treatment")))

# remove bulk soil outlier
rarefied_BacFun_ps_sampletype_l$Bac$bulk_soil<-subset_samples(rarefied_BacFun_ps_sampletype_l$Bac$bulk_soil, sample_names(rarefied_BacFun_ps_sampletype_l$Bac$bulk_soil) !="93B")




```


```{r}



# determine shannon diversity and observed number of taxa with a custom function
diversity_per_taxon <- function(ps_object, taxa_level, data_partition) {
  # this function provides diversity of each taxon in a phyloseq object in 3 steps
  
# the inputs for this function are: 
  
  # 1 - ps_object = one phyloseq object 
  # 2 - taxa_level = a QUOTED taxonomic level in your phyloseq object, like Class or Order
  # 3 - data_partition = a QUOTED label of your ps_object

# the output is a df showing observed number fo taxa and shannon diversity within each of the defined taxa_level 

# let's remove the "r__"ranks from the taxonomy, they can be useful but will polute our plot
tax_table(ps_object)[, colnames(tax_table(ps_object))] <- gsub(tax_table(ps_object)[, colnames(tax_table(ps_object))],     pattern = "[a-z]__", replacement = "")
  
  
  
# step 1: list the taxa present in the ps object, at the requested taxon level    
taxon_list_output<-as.character(tax_table(ps_object)[,taxa_level])
taxon_list_output<-taxon_list_output[taxon_list_output != "uncultured"]
taxon_list_output<-names(which(table(taxon_list_output)>0))%>%
na.omit()%>%
unique()%>%
as.list(c())
  


# step 2: calculate diversity in each member of the taxa level
shannon_diversity_l<-list()
observed_taxa_l<-list()
simpson_diversity_l<-list()
for(i in taxon_list_output) {
shannon_diversity_l[i]<-estimate_richness(prune_taxa(taxa = tax_table(ps_object)
                                                            [,taxa_level] %in% i,
                                                     x= ps_object),
                                          split = FALSE,
                                          measures = "Shannon" )

observed_taxa_l[i]<-estimate_richness(prune_taxa(taxa = tax_table(ps_object)
                                                        [,taxa_level] %in% i,
                                                 x= ps_object),
                                          split = FALSE,
                                          measures = "Observed" )

simpson_diversity_l[i]<-estimate_richness(prune_taxa(taxa = tax_table(ps_object)
                                                        [,taxa_level] %in% i,
                                                 x= ps_object),
                                          split = FALSE,
                                          measures = "Simpson" )
}


# step 3: join oserved taxa and shannon diversity in a df
shannon_df<-t(as.data.frame(shannon_diversity_l))
observed_df<-t(as.data.frame(observed_taxa_l))
simpson_df<-t(as.data.frame(simpson_diversity_l))
colnames(shannon_df)<-paste0("Shannon_", data_partition, sep = "")
colnames(observed_df)<-paste0("Observed_", data_partition, sep = "")
colnames(simpson_df)<-paste0("Simpson_", data_partition, sep = "")

#i had to join the df in separate steps. I'm sure this is not a cleaver way to do it but it works well enought
diversity_df<-merge(shannon_df,
                    observed_df,
                    by = 0)

diversity_df2<-merge(shannon_df,
                    simpson_df,
                    by = 0)



colnames(diversity_df)[1]<-taxa_level
colnames(diversity_df2)[1]<-taxa_level

output<-dplyr::left_join(diversity_df, diversity_df2)



return(output)
}

# it is a bit repetitive but I ran out of time to further automate this

###########################
####### class level ####### 
###########################
composted_frass_Class<-lapply(rarefied_BacFun_ps_sampletype_FrassTrestemnt_l$Bac[c(1,3)], function (x) # composted frass samples
  diversity_per_taxon(ps_object = x,
                      taxa_level = "Class",
                      data_partition = "composted_frass"))

Uncomposted_frass_Class<-lapply(rarefied_BacFun_ps_sampletype_FrassTrestemnt_l$Bac[c(2,4)], function (x) # uncomposted frass samples
  diversity_per_taxon(ps_object = x,
                      taxa_level = "Class",
                      data_partition = "Uncomposted_frass"))

# join 2 dfs of step 3
full_VS_selected_Class<-mapply(function (x,y)
  left_join(x,
            y,
            by = "Class"),
  x = composted_frass_Class,
  y = Uncomposted_frass_Class,
  SIMPLIFY = FALSE)






###########################
####### Order level ####### 
###########################
composted_frass_Order<-lapply(rarefied_BacFun_ps_sampletype_FrassTrestemnt_l$Bac[c(1,3)], function (x)
  diversity_per_taxon(ps_object = x,
                      taxa_level = "Order",
                      data_partition = "composted_frass"))

Uncomposted_frass_Order<-lapply(rarefied_BacFun_ps_sampletype_FrassTrestemnt_l$Bac[c(2,4)], function (x)
  diversity_per_taxon(ps_object = x,
                      taxa_level = "Order",
                      data_partition = "Uncomposted_frass"))

# join 2 dfs of step 3
full_VS_selected_Order<-mapply(function (x,y)
  left_join(x,
            y,
            by = "Order"),
  x = composted_frass_Order,
  y = Uncomposted_frass_Order,
  SIMPLIFY = FALSE)






###########################
####### Family level ###### 
###########################
composted_frass_Family<-lapply(rarefied_BacFun_ps_sampletype_FrassTrestemnt_l$Bac[c(1,3)], function (x)
  diversity_per_taxon(ps_object = x,
                      taxa_level = "Family",
                      data_partition = "composted_frass"))

Uncomposted_frass_Family<-lapply(rarefied_BacFun_ps_sampletype_FrassTrestemnt_l$Bac[c(2,4)], function (x)
  diversity_per_taxon(ps_object = x,
                      taxa_level = "Family",
                      data_partition = "Uncomposted_frass"))

# join 2 dfs of step 3
full_VS_selected_Family<-mapply(function (x,y)
  left_join(x,
            y,
            by = "Family"),
  x = composted_frass_Family,
  y = Uncomposted_frass_Family,
  SIMPLIFY = FALSE)

####################################################
####### Done! Diversity per taxon calculated ####### 
####################################################


# final output from divesity per taxon calculation
full_VS_selected_Class
full_VS_selected_Order
full_VS_selected_Family


# make plot - correlation between observed umber of taxa in the full data VS selected subset
plot_observed_correlation<-function(full_VS_selected_TaxaLevel){
untitled_plot_list<-lapply(full_VS_selected_TaxaLevel, function(z)
ggplot(data=z,aes(x=Observed_Uncomposted_frass,y=Observed_composted_frass ))+
  geom_point() +
  theme_bw()+
  theme(axis.title=element_text(size=11, face = "bold"))+
  xlab(label = "Number of taxa in uncomposted frass")+
  ylab(label = "Number of taxa in composted frass")+
  geom_smooth(method="loess")+ #values of y are based on the values of x
  geom_text_repel(aes(label=z[z$Observed_composted_frass>10,1]), data = z[z$Observed_composted_frass>10,], size = 3))

tiles_list<-names(untitled_plot_list) 

Plot_list<-mapply(function (x,z) # use mapply again to put those listed names in the list of plots
  x + ggtitle(z),
  x = untitled_plot_list,
  z = tiles_list, 
  SIMPLIFY = FALSE)
return(Plot_list)

}

plot_l_obs_Class <- plot_observed_correlation(full_VS_selected_Class)
plot_l_obs_Order <-plot_observed_correlation(full_VS_selected_Order)
plot_l_obs_Family <-plot_observed_correlation(full_VS_selected_Family)





plot_shannon_correlation<-function(full_VS_selected_TaxaLevel){
untitled_plot_list<-lapply(full_VS_selected_TaxaLevel, function(z)
ggplot(data=z[z$Shannon_composted_frass>0,], #only includes shannon >0
       aes(x=Shannon_Uncomposted_frass,y=Shannon_composted_frass ))+
  geom_point() +
   theme_bw()+
  theme(axis.title=element_text(size=11, face = "bold"))+
    xlab(label = "Shannon diversity in uncomposted frass")+
  ylab(label = "Shannon diversity in composted frass")+
  geom_smooth(method="loess")+ #values of y are based on the values of x
    geom_text_repel(aes(label=z[z$Shannon_composted_frass>0,1]), data = z[z$Shannon_composted_frass>0,], size = 3))

tiles_list<-names(untitled_plot_list) 

Plot_list<-mapply(function (x,z) # use mapply again to put those listed names in the list of plots
  x + ggtitle(z),
  x = untitled_plot_list,
  z = tiles_list, 
  SIMPLIFY = FALSE)
return(Plot_list)
}

plot_l_Shan_Class <- plot_shannon_correlation(full_VS_selected_Class)
plot_l_Shan_Order <- plot_shannon_correlation(full_VS_selected_Order)
plot_l_Shan_Family <- plot_shannon_correlation(full_VS_selected_Family)




plot_simpson_correlation<-function(full_VS_selected_TaxaLevel){
untitled_plot_list<-lapply(full_VS_selected_TaxaLevel, function(z)
ggplot(data=z[z$Simpson_composted_frass>0,], #only includes shannon >0
       aes(x=Simpson_Uncomposted_frass,y=Simpson_composted_frass ))+
  geom_point() +
   theme_bw()+
  theme(axis.title=element_text(size=11, face = "bold"))+
  xlab(label = "Simpson diversity in uncomposted frass")+
  ylab(label = "Simpson diversity in composted frass")+
  geom_smooth(method="loess")+ #values of y are based on the values of x
    geom_text_repel(aes(label=z[z$Simpson_composted_frass >0,1]), data = z[z$Simpson_composted_frass >0,], size = 3))

tiles_list<-names(untitled_plot_list) 

Plot_list<-mapply(function (x,z) # use mapply again to put those listed names in the list of plots
  x + ggtitle(z),
  x = untitled_plot_list,
  z = tiles_list, 
  SIMPLIFY = FALSE)
return(Plot_list)
}

plot_l_Simp_Class <- plot_simpson_correlation(full_VS_selected_Class)
plot_l_Simp_Order <- plot_simpson_correlation(full_VS_selected_Order)
plot_l_Simp_Family <- plot_simpson_correlation(full_VS_selected_Family)



#check how much$ of the taxa diversity is retained

full_VS_selected_Order$uni_4model_BO_above$Observed_composted_frass / full_VS_selected_Order$uni_4model_BO_above$Observed_Uncomposted_frass


# the loop for testing in each taxonomy class was not working properly, so i deleted the code for it!






```


#4.13 Figures
```{r}

library(gridExtra)

#Family
plot_AlphaCorr_Family <- grid.arrange(plot_l_obs_Family$bulk_soil.C, 
                                      plot_l_Shan_Family$bulk_soil.C,
                                      plot_l_Simp_Family$bulk_soil.C, 
                                      plot_l_obs_Family$rhizosphere.C, 
                                      plot_l_Shan_Family$rhizosphere.C, 
                                      plot_l_Simp_Family$rhizosphere.C, nrow=3,  ncol=3)

#save plot
ggsave(plot_AlphaCorr_Family,
       height = 24, width = 36,
       file="./Results/AlphaCorr_Family.svg")


#Order
plot_AlphaCorr_Order <- grid.arrange(plot_l_obs_Order$bulk_soil.C,
                                     plot_l_Shan_Order$bulk_soil.C,
                                     plot_l_Simp_Order$bulk_soil.C,
                                     plot_l_obs_Order$rhizosphere.C,
                                     plot_l_Shan_Order$rhizosphere.C,
                                     plot_l_Simp_Order$rhizosphere.C, nrow=3,  ncol=3)

#save plot
ggsave(plot_AlphaCorr_Order,
       height = 24, width = 36,
       file="./Results/AlphaCorr_Order.svg")


#Class 
plot_AlphaCorr_Class <- grid.arrange(plot_l_obs_Class$bulk_soil.C,
                                     plot_l_Shan_Class$bulk_soil.C,
                                     plot_l_Simp_Class$bulk_soil.C,
                                     plot_l_obs_Class$rhizosphere.C,
                                     plot_l_Shan_Class$rhizosphere.C,
                                     plot_l_Simp_Class$rhizosphere.C, nrow=3,  ncol=3)

#save plot
ggsave(plot_AlphaCorr_Class,
       height = 24, width = 36,
       file="./Results/AlphaCorr_Class.svg")


```

